name: CI & Publish to NuGet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Restore dependencies
        run: dotnet restore EasyMediator.sln

      - name: Build
        run: dotnet build EasyMediator.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test EasyMediator.sln --no-build --configuration Release

      - name: Pack and Push NuGet
        if: github.ref == 'refs/heads/main'
        run: |
          dotnet pack src/EasyMediator/EasyMediator.csproj --configuration Release --no-build -o out
          dotnet nuget push out/*.nupkg \
            --api-key ${{ secrets.NUGET_EASYMEDIATOR_API_KEY }} \
            --source https://api.nuget.org/v3/index.json
